services:

  bot:
    container_name: blue
    image: mark09/kind:v3.0.3
    depends_on:
      - redis
    env_file:
      - ../.env

  redis:
    container_name: red
    image: redis/redis-stack-server:latest
