services:

  bot:
    container_name: blue
    build: .
    image: mark09/kind:test
    depends_on:
      - redis
    env_file:
      - ../.env

  redis:
    container_name: red
    image: redis/redis-stack-server:latest
